services:
  tts-webui:
    image: "ghcr.io/rsxdalv/tts-webui:main"
    restart: unless-stopped
    ports:
      - ${TTS_PORT:-7770}:7770
      # include React UI
      - ${UI_PORT:-3000}:3000
    container_name: tts-webui
    volumes:
      - ./data:/app/tts-webui/data
      - ./outputs:/app/tts-webui/outputs
      - ./favorites:/app/tts-webui/favorites
    # environment:
    #   # Disable hard requirements for CUDA version ("requirement error: unsatisfied condition [...]")
    #   # This might still lead to errors but allows to run some models even if CUDA version is not met
    #   # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html#nvidia-disable-require-environment-variable
    #   NVIDIA_DISABLE_REQUIRE: 1 
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]

  # for the future:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 1s
  #     timeout: 5s
  #     retries: 10
 